import {IFilter, IFilterItems} from "./types";

export const sort  = ["release-date", "popularity", "alphabetical"];
export const filter: IFilterItems = {
  category: [
    { id: 1, name: "mmorpg" },
    { id: 2, name: "shooter" },
    { id: 3, name: "strategy" },
    { id: 4, name: "moba" },
    { id: 5, name: "racing" },
    { id: 6, name: "sports" },
    { id: 7, name: "social" },
    { id: 8, name: "sandbox" },
    { id: 9, name: "open-world" },
    { id: 10, name: "survival" },
    { id: 11, name: "pvp" },
    { id: 12, name: "pve" },
    { id: 13, name: "pixel" },
    { id: 14, name: "voxel" },
    { id: 15, name: "zombie" },
    { id: 16, name: "turn-based" },
    { id: 17, name: "first-person" },
    { id: 18, name: "third-Person" },
    { id: 19, name: "top-down" },
    { id: 20, name: "tank" },
    { id: 21, name: "space" },
    { id: 22, name: "sailing" },
    { id: 23, name: "side-scroller" },
    { id: 24, name: "superhero" },
    { id: 25, name: "permadeath" },
    { id: 26, name: "card" },
    { id: 27, name: "battle-royale" },
    { id: 28, name: "mmo" },
    { id: 29, name: "mmofps" },
    { id: 30, name: "mmotps" },
    { id: 31, name: "3d" },
    { id: 32, name: "2d" },
    { id: 33, name: "anime" },
    { id: 34, name: "fantasy" },
    { id: 35, name: "sci-fi" },
    { id: 36, name: "fighting" },
    { id: 37, name: "action-rpg" },
    { id: 38, name: "action" },
    { id: 39, name: "military" },
    { id: 40, name: "martial-arts" },
    { id: 41, name: "flight" },
    { id: 42, name: "low-spec" },
    { id: 43, name: "tower-defense" },
    { id: 44, name: "horror" },
    { id: 45, name: "mmorts" }
  ],
  platform: [
    { id: 46, name: "pc" },
    { id: 47, name: "browser" },
  ],
  tag: [
    { id: 48, name: "mmorpg" },
    { id: 49, name: "shooter" },
    { id: 50, name: "strategy" },
    { id: 51, name: "moba" },
    { id: 52, name: "racing" },
    { id: 53, name: "sports" },
    { id: 54, name: "social" },
    { id: 55, name: "sandbox" },
    { id: 56, name: "open-world" },
    { id: 57, name: "survival" },
    { id: 58, name: "pvp" },
    { id: 59, name: "pve" },
    { id: 60, name: "pixel" },
    { id: 61, name: "voxel" },
    { id: 62, name: "zombie" },
    { id: 63, name: "turn-based" },
    { id: 64, name: "first-person" },
    { id: 65, name: "third-Person" },
    { id: 66, name: "top-down" },
    { id: 67, name: "tank" },
    { id: 68, name: "space" },
    { id: 69, name: "sailing" },
    { id: 70, name: "side-scroller" },
    { id: 71, name: "superhero" },
    { id: 72, name: "permadeath" },
    { id: 73, name: "card" },
    { id: 74, name: "battle-royale" },
    { id: 75, name: "mmo" },
    { id: 76, name: "mmofps" },
    { id: 77, name: "mmotps" },
    { id: 78, name: "3d" },
    { id: 79, name: "2d" },
    { id: 80, name: "anime" },
    { id: 81, name: "fantasy" },
    { id: 82, name: "sci-fi" },
    { id: 83, name: "fighting" },
    { id: 84, name: "action-rpg" },
    { id: 85, name: "action" },
    { id: 86, name: "military" },
    { id: 87, name: "martial-arts" },
    { id: 88, name: "flight" },
    { id: 89, name: "low-spec" },
    { id: 90, name: "tower-defense" },
    { id: 91, name: "horror" },
    { id: 92, name: "mmorts" }
  ]
}